// AUTO-GENERATED from site/examples/*.hcl by scripts/gen-examples.mjs.
// Do not edit by hand — change the .hcl file and regenerate.

export const approver_human = "approver \"human_approver\" \"ops\" {\n  channel    = \"#agent-ops\"\n  credential = slack-bot\n  timeout    = 600\n}\n\n# ===== harness =====\n\nadmin_email = \"ops@example.com\"\n\ncredential \"slack_tokens\" \"slack-bot\" {}\ncredential \"bearer_token\" \"noop\" {}\n\nendpoint \"https\" \"anchor\" {\n  hosts      = [\"example.com\"]\n  credential = noop\n}\n\nprofile \"default\" { endpoints = [anchor] }\n";
export const approver_llm = "approver \"llm_approver\" \"secret-judge\" {\n  model      = \"claude-haiku-4-5-20251001\"\n  credential = anthropic-key\n  policy     = secret-policy\n}\n\npolicy \"secret-policy\" {\n  text = \"Reject any SELECT that projects secret-bearing columns.\"\n}\n\n# ===== harness =====\n\nadmin_email = \"ops@example.com\"\n\ncredential \"anthropic_manual_key\" \"anthropic-key\" {}\ncredential \"bearer_token\" \"noop\" {}\n\nendpoint \"https\" \"anchor\" {\n  hosts      = [\"example.com\"]\n  credential = noop\n}\n\nprofile \"default\" { endpoints = [anchor] }\n";
export const protocol_https = "rule \"github-no-repo-delete\" {\n  endpoint  = github-api\n  condition = \"http.method == 'DELETE' && http.path.startsWith('/repos/')\"\n  verdict   = \"deny\"\n  reason    = \"deleting repos is not allowed\"\n}\n\n# ===== harness =====\n\nadmin_email = \"ops@example.com\"\n\ncredential \"bearer_token\" \"github-pat\" {}\n\nendpoint \"https\" \"github-api\" {\n  hosts      = [\"api.github.com\"]\n  credential = github-pat\n}\n\nprofile \"default\" { endpoints = [github-api] }\n";
export const protocol_k8s = "rule \"k8s-no-secrets\" {\n  endpoints = [k8s-dev, k8s-prod]\n  priority  = 1000\n  condition = \"k8s.resource == 'secrets'\"\n  verdict   = \"deny\"\n  reason    = \"secrets stay in the cluster\"\n}\n\n# ===== harness =====\n# Everything below is config scaffolding so `clawpatrol validate`\n# accepts this file. The landing page renders only the snippet above.\n\nadmin_email = \"ops@example.com\"\n\ncredential \"mtls_credential\" \"k8s-dev-cred\"  {}\ncredential \"mtls_credential\" \"k8s-prod-cred\" {}\n\nendpoint \"kubernetes\" \"k8s-dev\" {\n  server     = \"k8s-dev.example\"\n  credential = k8s-dev-cred\n}\n\nendpoint \"kubernetes\" \"k8s-prod\" {\n  server     = \"k8s-prod.example\"\n  credential = k8s-prod-cred\n}\n\nprofile \"default\" { endpoints = [k8s-dev, k8s-prod] }\n";
export const protocol_sql = "rule \"clickhouse-allow-read\" {\n  endpoints = [clickhouse-o11y]\n  condition = \"sql.verb in ['select', 'show', 'describe', 'explain', 'use', 'exists']\"\n  verdict   = \"allow\"\n}\n\n# ===== harness =====\n\nadmin_email = \"ops@example.com\"\n\ncredential \"clickhouse_credential\" \"ch-cred\" { user = \"agent\" }\n\nendpoint \"clickhouse_native\" \"clickhouse-o11y\" {\n  hosts      = [\"clickhouse.example\"]\n  credential = ch-cred\n}\n\nprofile \"default\" { endpoints = [clickhouse-o11y] }\n";
export const rules_block = "# Block destructive SQL on prod\nrule \"no-prod-drops\" {\n  endpoint  = pg-prod\n  condition = \"sql.verb in ['drop', 'truncate', 'alter']\"\n  verdict   = \"deny\"\n}\n\n# Slack-approve any GitHub write\nrule \"github-writes\" {\n  endpoint  = github-api\n  condition = \"http.method in ['POST', 'PUT', 'DELETE']\"\n  approve   = [ops]\n}\n\n# ===== harness =====\n\nadmin_email = \"ops@example.com\"\n\ncredential \"postgres_credential\" \"pg-cred\"    { user = \"agent\" }\ncredential \"bearer_token\"        \"github-pat\" {}\ncredential \"slack_tokens\"        \"slack-bot\"  {}\n\nendpoint \"postgres\" \"pg-prod\" {\n  host       = \"pg-prod.example:5432\"\n  credential = pg-cred\n}\n\nendpoint \"https\" \"github-api\" {\n  hosts      = [\"api.github.com\"]\n  credential = github-pat\n}\n\napprover \"human_approver\" \"ops\" {\n  channel    = \"#agent-ops\"\n  credential = slack-bot\n}\n\nprofile \"default\" { endpoints = [pg-prod, github-api] }\n";
